export type Category = 'AI' | 'Provider' | 'Logic' | 'Memory' | 'System' | 'Storage' | 'Triggers' | 'Canvas';

export interface NodeField {
  key: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'toggle' | 'slider' | 'textarea';
  options?: string[];
  min?: number;
  max?: number;
  step?: number;
  placeholder?: string;
}

export interface NodeDefinition {
  type: string;
  category: Category;
  label: string;
  description: string;
  icon: string;
  color: string;
  defaults: Record<string, unknown>;
  fields: NodeField[];
  outputHandles: 'single' | 'if';
  inputHandles: 'single' | 'none';
  simulate?: boolean;
}

export const CATEGORY_META: Record<Category, { color: string; swatch: string }> = {
  AI: { color: 'text-blue-400', swatch: 'bg-blue-500' },
  Provider: { color: 'text-cyan-400', swatch: 'bg-cyan-500' },
  Logic: { color: 'text-amber-400', swatch: 'bg-amber-500' },
  Memory: { color: 'text-emerald-400', swatch: 'bg-emerald-500' },
  System: { color: 'text-slate-400', swatch: 'bg-slate-500' },
  Storage: { color: 'text-teal-400', swatch: 'bg-teal-500' },
  Triggers: { color: 'text-rose-400', swatch: 'bg-rose-500' },
  Canvas: { color: 'text-yellow-400', swatch: 'bg-yellow-500' },
};

export const NODE_DEFINITIONS: NodeDefinition[] = [
  // ── Triggers ────────────────────────────────────────────────
  {
    type: 'trigger',
    category: 'Triggers',
    label: 'Trigger',
    description: 'Entry point — fires when a user request arrives.',
    icon: '🚀',
    color: 'bg-rose-500/15 text-rose-400 border-rose-500/30',
    defaults: { name: 'User Request' },
    fields: [{ key: 'name', label: 'Trigger name', type: 'text', placeholder: 'User Request' }],
    outputHandles: 'single',
    inputHandles: 'none',
  },
  {
    type: 'subscriptionCheck',
    category: 'Triggers',
    label: 'Subscription Check',
    description: 'Branches the flow by the user subscription plan.',
    icon: '🎫',
    color: 'bg-rose-500/15 text-rose-400 border-rose-500/30',
    defaults: { name: 'Plan Gate' },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }],
    outputHandles: 'if',
    inputHandles: 'single',
  },

  // ── AI ──────────────────────────────────────────────────────
  {
    type: 'chatModel',
    category: 'AI',
    label: 'Chat Model',
    description: 'Run an LLM call against any configured provider.',
    icon: '🧠',
    color: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
    defaults: { name: 'Chat Model', provider: 'OpenAI', model: 'gpt-4o-mini', temperature: 0.7, maxTokens: 1024, systemPrompt: '' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      {
        key: 'provider', label: 'Provider', type: 'select',
        options: ['OpenAI', 'Google Gemini', 'Anthropic', 'OpenRouter', 'Groq', 'DeepSeek', 'Together'],
      },
      { key: 'model', label: 'Model', type: 'text', placeholder: 'gpt-4o-mini' },
      { key: 'temperature', label: 'Temperature', type: 'slider', min: 0, max: 2, step: 0.1 },
      { key: 'maxTokens', label: 'Max tokens', type: 'number', min: 64, max: 32768, step: 64 },
      { key: 'systemPrompt', label: 'System prompt', type: 'textarea', placeholder: 'You are a helpful assistant…' },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
    simulate: true,
  },
  {
    type: 'imageModel',
    category: 'AI',
    label: 'Image Model',
    description: 'Generate images from a prompt.',
    icon: '🎨',
    color: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
    defaults: { name: 'Image Model', provider: 'Pollinations', model: 'flux', size: '1024x1024', count: 1, negativePrompt: '', chain: [] },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'provider', label: 'Provider', type: 'select', options: ['Pollinations', 'OpenAI', 'Stability'] },
      { key: 'model', label: 'Model', type: 'text', placeholder: 'flux' },
      { key: 'size', label: 'Size', type: 'select', options: ['512x512', '768x768', '1024x1024', '1536x1024'] },
      { key: 'count', label: 'Count', type: 'number', min: 1, max: 8, step: 1 },
      { key: 'negativePrompt', label: 'Negative prompt', type: 'textarea' },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
    simulate: true,
  },
  {
    type: 'videoModel',
    category: 'AI',
    label: 'Video Model',
    description: 'Generate short video clips.',
    icon: '🎬',
    color: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
    defaults: { name: 'Video Model', provider: 'Runway', model: 'gen-3', duration: 5 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'provider', label: 'Provider', type: 'select', options: ['Runway', 'Replicate', 'Fal'] },
      { key: 'model', label: 'Model', type: 'text', placeholder: 'gen-3' },
      { key: 'duration', label: 'Duration (s)', type: 'number', min: 2, max: 20, step: 1 },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
    simulate: true,
  },
  {
    type: 'audioModel',
    category: 'AI',
    label: 'Audio Model',
    description: 'Music / sound generation.',
    icon: '🎵',
    color: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
    defaults: { name: 'Audio Model', provider: 'Replicate', model: 'musicgen' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'provider', label: 'Provider', type: 'select', options: ['Replicate', 'Fal'] },
      { key: 'model', label: 'Model', type: 'text', placeholder: 'musicgen' },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
    simulate: true,
  },
  {
    type: 'embeddingModel',
    category: 'AI',
    label: 'Embedding Model',
    description: 'Turn text into vector embeddings.',
    icon: '🧩',
    color: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
    defaults: { name: 'Embedding', provider: 'OpenAI', model: 'text-embedding-3-small' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'provider', label: 'Provider', type: 'select', options: ['OpenAI', 'Google Gemini'] },
      { key: 'model', label: 'Model', type: 'text', placeholder: 'text-embedding-3-small' },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
    simulate: true,
  },
  {
    type: 'ocr',
    category: 'AI',
    label: 'OCR',
    description: 'Extract text from images or PDFs.',
    icon: '🔤',
    color: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
    defaults: { name: 'OCR', provider: 'OpenAI' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'provider', label: 'Provider', type: 'select', options: ['OpenAI', 'Google Gemini'] },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
    simulate: true,
  },
  {
    type: 'speechToText',
    category: 'AI',
    label: 'Speech to Text',
    description: 'Transcribe audio input.',
    icon: '🎙️',
    color: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
    defaults: { name: 'STT', provider: 'OpenAI', model: 'whisper-1' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'provider', label: 'Provider', type: 'select', options: ['OpenAI', 'Groq'] },
      { key: 'model', label: 'Model', type: 'text', placeholder: 'whisper-1' },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
    simulate: true,
  },
  {
    type: 'textToSpeech',
    category: 'AI',
    label: 'Text to Speech',
    description: 'Synthesize voice from text.',
    icon: '🔊',
    color: 'bg-blue-500/15 text-blue-400 border-blue-500/30',
    defaults: { name: 'TTS', provider: 'OpenAI', model: 'tts-1', voice: 'alloy' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'provider', label: 'Provider', type: 'select', options: ['OpenAI', 'Google Gemini'] },
      { key: 'model', label: 'Model', type: 'text', placeholder: 'tts-1' },
      { key: 'voice', label: 'Voice', type: 'select', options: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer'] },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
    simulate: true,
  },

  // ── Providers ───────────────────────────────────────────────
  {
    type: 'openai', category: 'Provider', label: 'OpenAI', description: 'OpenAI GPT / image / audio APIs.',
    icon: '⚡', color: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    defaults: { name: 'OpenAI', apiKey: '', baseUrl: 'https://api.openai.com/v1', maxRpm: 60, maxTpm: 100000, priority: 1 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'apiKey', label: 'API key', type: 'text', placeholder: 'sk-…' },
      { key: 'baseUrl', label: 'Base URL', type: 'text' },
      { key: 'maxRpm', label: 'Max RPM', type: 'number', min: 1, max: 10000 },
      { key: 'maxTpm', label: 'Max TPM', type: 'number', min: 1000, max: 10000000, step: 1000 },
      { key: 'priority', label: 'Priority', type: 'number', min: 1, max: 10, step: 1 },
    ],
    outputHandles: 'single', inputHandles: 'single',
  },
  {
    type: 'gemini', category: 'Provider', label: 'Google Gemini', description: 'Gemini multimodal models.',
    icon: '💫', color: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    defaults: { name: 'Google Gemini', apiKey: '', baseUrl: 'https://generativelanguage.googleapis.com/v1beta', maxRpm: 60, maxTpm: 250000, priority: 2 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'apiKey', label: 'API key', type: 'text' },
      { key: 'baseUrl', label: 'Base URL', type: 'text' },
      { key: 'maxRpm', label: 'Max RPM', type: 'number', min: 1, max: 10000 },
      { key: 'maxTpm', label: 'Max TPM', type: 'number', min: 1000, max: 10000000, step: 1000 },
      { key: 'priority', label: 'Priority', type: 'number', min: 1, max: 10 },
    ],
    outputHandles: 'single', inputHandles: 'single',
  },
  {
    type: 'anthropic', category: 'Provider', label: 'Anthropic', description: 'Claude models.',
    icon: '✨', color: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    defaults: { name: 'Anthropic', apiKey: '', baseUrl: 'https://api.anthropic.com/v1', maxRpm: 60, maxTpm: 100000, priority: 3 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'apiKey', label: 'API key', type: 'text' },
      { key: 'baseUrl', label: 'Base URL', type: 'text' },
      { key: 'maxRpm', label: 'Max RPM', type: 'number', min: 1, max: 10000 },
      { key: 'maxTpm', label: 'Max TPM', type: 'number', min: 1000, max: 10000000, step: 1000 },
      { key: 'priority', label: 'Priority', type: 'number', min: 1, max: 10 },
    ],
    outputHandles: 'single', inputHandles: 'single',
  },
  {
    type: 'openrouter', category: 'Provider', label: 'OpenRouter', description: 'Unified gateway to hundreds of models.',
    icon: '🧭', color: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    defaults: { name: 'OpenRouter', apiKey: '', baseUrl: 'https://openrouter.ai/api/v1', maxRpm: 60, maxTpm: 50000, priority: 4 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'apiKey', label: 'API key', type: 'text' },
      { key: 'baseUrl', label: 'Base URL', type: 'text' },
      { key: 'maxRpm', label: 'Max RPM', type: 'number', min: 1, max: 10000 },
      { key: 'maxTpm', label: 'Max TPM', type: 'number', min: 1000, max: 10000000, step: 1000 },
      { key: 'priority', label: 'Priority', type: 'number', min: 1, max: 10 },
    ],
    outputHandles: 'single', inputHandles: 'single',
  },
  {
    type: 'groq', category: 'Provider', label: 'Groq', description: 'Ultra-fast inference on LPU hardware.',
    icon: '🏎️', color: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    defaults: { name: 'Groq', apiKey: '', baseUrl: 'https://api.groq.com/openai/v1', maxRpm: 100, maxTpm: 6000, priority: 5 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'apiKey', label: 'API key', type: 'text' },
      { key: 'baseUrl', label: 'Base URL', type: 'text' },
      { key: 'maxRpm', label: 'Max RPM', type: 'number', min: 1, max: 10000 },
      { key: 'maxTpm', label: 'Max TPM', type: 'number', min: 1000, max: 10000000, step: 1000 },
      { key: 'priority', label: 'Priority', type: 'number', min: 1, max: 10 },
    ],
    outputHandles: 'single', inputHandles: 'single',
  },
  {
    type: 'deepseek', category: 'Provider', label: 'DeepSeek', description: 'DeepSeek reasoning models.',
    icon: '🪷', color: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    defaults: { name: 'DeepSeek', apiKey: '', baseUrl: 'https://api.deepseek.com/v1', maxRpm: 30, maxTpm: 60000, priority: 6 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'apiKey', label: 'API key', type: 'text' },
      { key: 'baseUrl', label: 'Base URL', type: 'text' },
      { key: 'maxRpm', label: 'Max RPM', type: 'number', min: 1, max: 10000 },
      { key: 'maxTpm', label: 'Max TPM', type: 'number', min: 1000, max: 10000000, step: 1000 },
      { key: 'priority', label: 'Priority', type: 'number', min: 1, max: 10 },
    ],
    outputHandles: 'single', inputHandles: 'single',
  },
  {
    type: 'together', category: 'Provider', label: 'Together', description: 'Open-source model cloud.',
    icon: '🫂', color: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    defaults: { name: 'Together', apiKey: '', baseUrl: 'https://api.together.xyz/v1', maxRpm: 60, maxTpm: 20000, priority: 7 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'apiKey', label: 'API key', type: 'text' },
      { key: 'baseUrl', label: 'Base URL', type: 'text' },
      { key: 'maxRpm', label: 'Max RPM', type: 'number', min: 1, max: 10000 },
      { key: 'maxTpm', label: 'Max TPM', type: 'number', min: 1000, max: 10000000, step: 1000 },
      { key: 'priority', label: 'Priority', type: 'number', min: 1, max: 10 },
    ],
    outputHandles: 'single', inputHandles: 'single',
  },
  {
    type: 'replicate', category: 'Provider', label: 'Replicate', description: 'Community model marketplace.',
    icon: '♻️', color: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    defaults: { name: 'Replicate', apiKey: '', baseUrl: 'https://api.replicate.com/v1', maxRpm: 60, maxTpm: 10000, priority: 8 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'apiKey', label: 'API key', type: 'text' },
      { key: 'baseUrl', label: 'Base URL', type: 'text' },
      { key: 'maxRpm', label: 'Max RPM', type: 'number', min: 1, max: 10000 },
      { key: 'priority', label: 'Priority', type: 'number', min: 1, max: 10 },
    ],
    outputHandles: 'single', inputHandles: 'single',
  },
  {
    type: 'fal', category: 'Provider', label: 'Fal', description: 'Serverless AI inference.',
    icon: '🦅', color: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    defaults: { name: 'Fal', apiKey: '', baseUrl: 'https://fal.run', maxRpm: 60, maxTpm: 10000, priority: 9 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'apiKey', label: 'API key', type: 'text' },
      { key: 'baseUrl', label: 'Base URL', type: 'text' },
      { key: 'maxRpm', label: 'Max RPM', type: 'number', min: 1, max: 10000 },
      { key: 'priority', label: 'Priority', type: 'number', min: 1, max: 10 },
    ],
    outputHandles: 'single', inputHandles: 'single',
  },
  {
    type: 'stability', category: 'Provider', label: 'Stability', description: 'Stable Diffusion image APIs.',
    icon: '🖼️', color: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/30',
    defaults: { name: 'Stability', apiKey: '', baseUrl: 'https://api.stability.ai/v1', maxRpm: 30, maxTpm: 10000, priority: 10 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'apiKey', label: 'API key', type: 'text' },
      { key: 'baseUrl', label: 'Base URL', type: 'text' },
      { key: 'maxRpm', label: 'Max RPM', type: 'number', min: 1, max: 10000 },
      { key: 'priority', label: 'Priority', type: 'number', min: 1, max: 10 },
    ],
    outputHandles: 'single', inputHandles: 'single',
  },

  // ── Logic ───────────────────────────────────────────────────
  {
    type: 'if',
    category: 'Logic',
    label: 'If',
    description: 'Branch the flow based on a condition.',
    icon: '🔀',
    color: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    defaults: { name: 'If', condition: 'equals', field: 'plan', value: '' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'field', label: 'Field', type: 'text', placeholder: 'plan' },
      { key: 'condition', label: 'Condition', type: 'select', options: ['equals', 'contains', 'greaterThan', 'lessThan', 'isSet'] },
      { key: 'value', label: 'Value', type: 'text', placeholder: 'premium' },
    ],
    outputHandles: 'if',
    inputHandles: 'single',
  },
  {
    type: 'else',
    category: 'Logic',
    label: 'Else',
    description: 'Fallback branch taken when conditions fail.',
    icon: '⤵️',
    color: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    defaults: { name: 'Else' },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'switch',
    category: 'Logic',
    label: 'Switch',
    description: 'Multi-way branching on a field.',
    icon: '🎚️',
    color: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    defaults: { name: 'Switch', field: 'payload.tier' },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }, { key: 'field', label: 'Field', type: 'text', placeholder: 'payload.tier' }],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'wait',
    category: 'Logic',
    label: 'Wait',
    description: 'Pause execution for a given time.',
    icon: '⏳',
    color: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    defaults: { name: 'Wait', seconds: 2 },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }, { key: 'seconds', label: 'Seconds', type: 'number', min: 0, max: 600 }],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'delay',
    category: 'Logic',
    label: 'Delay',
    description: 'Insert artificial latency (rate limiting).',
    icon: '🐢',
    color: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    defaults: { name: 'Delay', ms: 300 },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }, { key: 'ms', label: 'Milliseconds', type: 'number', min: 0, max: 60000, step: 50 }],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'retry',
    category: 'Logic',
    label: 'Retry',
    description: 'Retry upstream calls, then route to fallback on repeated failure.',
    icon: '🔁',
    color: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    defaults: { name: 'Retry', attempts: 2, delayMs: 500, onError: 'next' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'attempts', label: 'Attempts', type: 'number', min: 1, max: 5, step: 1 },
      { key: 'delayMs', label: 'Retry delay (ms)', type: 'number', min: 100, max: 30000, step: 100 },
      { key: 'onError', label: 'On repeated failure', type: 'select', options: ['next', 'stop'] },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'loop',
    category: 'Logic',
    label: 'Loop',
    description: 'Repeat the downstream branch N times.',
    icon: '🔄',
    color: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    defaults: { name: 'Loop', maxIterations: 3 },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }, { key: 'maxIterations', label: 'Max iterations', type: 'number', min: 1, max: 100 }],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'parallel',
    category: 'Logic',
    label: 'Parallel',
    description: 'Fan out to multiple branches concurrently.',
    icon: '⚡',
    color: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    defaults: { name: 'Parallel' },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'merge',
    category: 'Logic',
    label: 'Merge',
    description: 'Join parallel branches back together.',
    icon: '⋈',
    color: 'bg-amber-500/15 text-amber-400 border-amber-500/30',
    defaults: { name: 'Merge' },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }],
    outputHandles: 'single',
    inputHandles: 'single',
  },

  // ── Memory ──────────────────────────────────────────────────
  {
    type: 'cache',
    category: 'Memory',
    label: 'Cache',
    description: 'Short-term key/value cache.',
    icon: '💾',
    color: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30',
    defaults: { name: 'Cache', ttlSeconds: 300 },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }, { key: 'ttlSeconds', label: 'TTL (s)', type: 'number', min: 1, max: 86400 }],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'redis',
    category: 'Memory',
    label: 'Redis',
    description: 'Shared external key/value store.',
    icon: '🗄️',
    color: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30',
    defaults: { name: 'Redis', connection: 'default', ttlSeconds: 3600 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'connection', label: 'Connection', type: 'text', placeholder: 'default' },
      { key: 'ttlSeconds', label: 'TTL (s)', type: 'number', min: 1, max: 604800 },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'history',
    category: 'Memory',
    label: 'Chat History',
    description: 'Conversation history store.',
    icon: '📚',
    color: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30',
    defaults: { name: 'Chat History', maxMessages: 20 },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }, { key: 'maxMessages', label: 'Max messages', type: 'number', min: 1, max: 200 }],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'session',
    category: 'Memory',
    label: 'Session',
    description: 'Per-user session storage.',
    icon: '👤',
    color: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30',
    defaults: { name: 'Session', ttlMinutes: 60 },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }, { key: 'ttlMinutes', label: 'TTL (min)', type: 'number', min: 1, max: 10080 }],
    outputHandles: 'single',
    inputHandles: 'single',
  },

  // ── System ──────────────────────────────────────────────────
  {
    type: 'logger',
    category: 'System',
    label: 'Logger',
    description: 'Emit structured log output.',
    icon: '📋',
    color: 'bg-slate-500/15 text-slate-300 border-slate-500/30',
    defaults: { name: 'Logger', level: 'info', message: 'Node executed' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'level', label: 'Level', type: 'select', options: ['debug', 'info', 'warn', 'error'] },
      { key: 'message', label: 'Message', type: 'text' },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'analytics',
    category: 'System',
    label: 'Analytics',
    description: 'Record metrics for dashboards.',
    icon: '📊',
    color: 'bg-slate-500/15 text-slate-300 border-slate-500/30',
    defaults: { name: 'Analytics', track: 'request' },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }, { key: 'track', label: 'Track', type: 'select', options: ['request', 'cost', 'latency', 'usage'] }],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'errorHandler',
    category: 'System',
    label: 'Error Handler',
    description: 'Catch and route failures from upstream nodes.',
    icon: '🛡️',
    color: 'bg-slate-500/15 text-slate-300 border-slate-500/30',
    defaults: { name: 'Error Handler', action: 'stop' },
    fields: [{ key: 'name', label: 'Node name', type: 'text' }, { key: 'action', label: 'Action', type: 'select', options: ['stop', 'continue', 'fallback'] }],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'notification',
    category: 'System',
    label: 'Notification',
    description: 'Push alerts via email, webhook or push.',
    icon: '🔔',
    color: 'bg-slate-500/15 text-slate-300 border-slate-500/30',
    defaults: { name: 'Notification', channel: 'webhook', target: '' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'channel', label: 'Channel', type: 'select', options: ['email', 'webhook', 'push'] },
      { key: 'target', label: 'Target', type: 'text', placeholder: 'https://…' },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
  },
  {
    type: 'rateLimiter',
    category: 'System',
    label: 'Rate Limiter',
    description: 'Enforce RPM budgets on downstream calls.',
    icon: '🚦',
    color: 'bg-slate-500/15 text-slate-300 border-slate-500/30',
    defaults: { name: 'Rate Limiter', rpm: 60, burst: 120 },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'rpm', label: 'RPM', type: 'number', min: 1, max: 10000 },
      { key: 'burst', label: 'Burst', type: 'number', min: 1, max: 20000 },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
  },

  // ── Storage ─────────────────────────────────────────────────
  {
    type: 'storage',
    category: 'Storage',
    label: 'Storage',
    description: 'Persist outputs to cloud storage.',
    icon: '☁️',
    color: 'bg-teal-500/15 text-teal-400 border-teal-500/30',
    defaults: { name: 'Storage', storage: 'Local', path: '/outputs' },
    fields: [
      { key: 'name', label: 'Node name', type: 'text' },
      { key: 'storage', label: 'Storage', type: 'select', options: ['Local', 'Google Drive', 'S3', 'Cloudflare R2'] },
      { key: 'path', label: 'Path', type: 'text', placeholder: '/outputs' },
    ],
    outputHandles: 'single',
    inputHandles: 'single',
  },

  // ── Canvas ──────────────────────────────────────────────────
  {
    type: 'note',
    category: 'Canvas',
    label: 'Sticky Note',
    description: 'Yellow note for documentation on the canvas.',
    icon: '🗒️',
    color: 'bg-yellow-500/15 text-yellow-400 border-yellow-500/30',
    defaults: { name: 'Note', text: 'Type a note…' },
    fields: [{ key: 'text', label: 'Note text', type: 'textarea', placeholder: 'Write something…' }],
    outputHandles: 'single',
    inputHandles: 'none',
  },
  {
    type: 'group',
    category: 'Canvas',
    label: 'Group',
    description: 'Dashed frame to organize groups of nodes.',
    icon: '🗂️',
    color: 'bg-yellow-500/15 text-yellow-400 border-yellow-500/30',
    defaults: { name: 'Group', width: 480, height: 320 },
    fields: [
      { key: 'title', label: 'Group title', type: 'text', placeholder: 'Untitled group' },
      { key: 'width', label: 'Width', type: 'number', min: 200, max: 2000, step: 10 },
      { key: 'height', label: 'Height', type: 'number', min: 120, max: 1500, step: 10 },
    ],
    outputHandles: 'single',
    inputHandles: 'none',
  },
];

const byType = new Map(NODE_DEFINITIONS.map((d) => [d.type, d]));

export function getNodeDefinition(type: string): NodeDefinition {
  return (
    byType.get(type) ?? {
      type,
      category: 'System',
      label: type,
      description: 'Unknown node type',
      icon: '❓',
      color: 'bg-slate-500/15 text-slate-300 border-slate-500/30',
      defaults: {},
      fields: [],
      outputHandles: 'single',
      inputHandles: 'single',
    }
  );
}

export const CATEGORY_ORDER: Category[] = ['AI', 'Provider', 'Logic', 'Memory', 'System', 'Storage', 'Triggers', 'Canvas'];
